version: "3.8"

services:
  db:
    image: postgres:15
    container_name: amadin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpass}
      POSTGRES_DB: ${POSTGRES_DB:-devdb}
    ports:
      - "5433:5432"
    volumes:
      - amadin_pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  amadin_pgdata:
